###
GET http://localhost:8121/users
###
GET http://localhost:8121/users/63d5d900044ff54c3dba064d

### Create contact 
POST http://localhost:8121/users HTTP/1.1 
content-type: application/json

{
  "username": "Dream",
  "firstName": "Viry",
  "lastName": "Rocha",
  "email": "viry@test.com",
  "password": "Viry!Password"
}

### Update contact 
PUT http://localhost:8121/users/63d5dea2140813ea5c955d58 HTTP/1.1 
content-type: application/json

{
  "username": "Dream",
  "firstName": "Viry",
  "lastName": "Torres",
  "email": "viry@test.com",
  "password": "Viry!Password"
}


### DELETE contact
DELETE http://localhost:8121/foods/63d5dea2140813ea5c955d58 HTTP/1.1
###
###
GET http://localhost:8121/foods
###
GET http://localhost:8121/
###
GET http://localhost:8121/foods/63c8b8f345e0548045c2d8c8
###
GET http://localhost:8121/foods/63c8b8f345e0548045c2d8cd

### Create contact 
POST http://localhost:8121/foods HTTP/1.1 
content-type: application/json

{
    "food_category": "Fruit",
    "food_name": "Melon",
    "protein_gr": "2.0",
    "carbs_gr": "12.0",
    "fat_gr": "0.0",
    "fiber_gr": "2.0",
    "food_portion": "1 piece",
    "calories": "60"
}
### Update contact 
PUT http://localhost:8121/foods/63cb510749604fc5654829f8 HTTP/1.1 
content-type: application/json

{
    "food_category": "fat",
    "food_name": "Peanut Butter",
    "protein_gr": "0.0",
    "carbs_gr": "0.0",
    "fat_gr": "5.0",
    "fiber_gr": "0.0",
    "food_portion": "1 tablespoon",
    "calories": "45"
}
### Delete contact 
### DELETE contact
DELETE http://localhost:8121/foods/63cb0d47326d2ee018c9320a HTTP/1.1
###
GET https://food-l5.onrender.com/

// PRODUCTION Deploy
###
GET https://food-l5.onrender.com/foods
###
GET https://food-l5.onrender.com/foods/63c8b8f345e0548045c2d8cb
###
GET https://food-l5.onrender.com/foods/63c8b8f345e0548045c2d8cb
###
GET https://food-l5.onrender.com/foods/63c8b8f345e0548045c2d8cb
###
POST http://food-l5.onrender.com/foods HTTP/1.1 
content-type: application/json

{
"food_category": "Fat",
    "food_name": "test",
    "protein_gr": "0.0",
    "carbs_gr": "0.0",
    "fat_gr": "5.0",
    "fiber_gr": "0.0",
    "food_portion": "1 tablespoon",
    "calories": "25.0"
}
###
PUT http://food-l5.onrender.com/foods/63c8b8f345e0548045c2d8cd HTTP/1.1 
content-type: application/json

{
"food_category": "Fat",
    "food_name": "Avocado",
    "protein_gr": "0.0",
    "carbs_gr": "0.0",
    "fat_gr": "5.0",
    "fiber_gr": "0.0",
    "food_portion": "1/4 of piece",
    "calories": "50.0"
}
###
DELETE http://food-l5.onrender.com/foods/63c8f67d5832c03da87a5c6a HTTP/1.1



###
GET https://food-l5.onrender.com/

// PRODUCTION Deploy
###
GET https://food-l5.onrender.com/users
###
GET https://food-l5.onrender.com/users/63d5dea2140813ea5c955d58
###
POST http://food-l5.onrender.com/users HTTP/1.1 
content-type: application/json

{
  "username": "Dream",
  "firstName": "Viry",
  "lastName": "Rocha",
  "email": "viry@test.com",
  "password": "Viry!Password"
}

###
PUT http://food-l5.onrender.com/users/63d5dea2140813ea5c955d58 HTTP/1.1 
content-type: application/json

{
  "username": "Dream",
  "firstName": "Viry",
  "lastName": "Torres",
  "email": "viry@test.com",
  "password": "Viry!Password"
}

###
DELETE http://food-l5.onrender.com/users/63d5dea2140813ea5c955d58 HTTP/1.1